spring:
  application:
    name: WealthTech
  datasource:
    url: jdbc:postgresql://localhost:5432/wealthtech
    username: wealthtech
    password: wealthtech
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

enrichment:
  scheduler:
    fixed-delay-ms: 5000
  processor:
    pool-size: 4
    timeout-ms: 30000
